import { Task } from "@/interfaces/ITaskPlanner";

export const tasks : Task[] = [
  {
    id: 1,
    title: "Finish project report",
    category: "Work",
    description: "",
    color: "#224A1C",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 2,
    title: "Grocery shopping",
    category: "Personal",
    description: "",
    color: "#4148CC",
    completed: true,
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 3,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 4,
    title: "Workout session",
    category: "Personal",
    description: "",
    color: "#4148CC",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 5,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 6,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 7,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 8,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 9,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 10,
    title: "Workout session",
    category: "Goal",
    description: "",
    color: "#BB7A00",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 11,
    title: "Workout session",
    category: "Work",
    description: "",
    color: "#224A1C",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 12,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 13,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 14,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  },
  {
    id: 15,
    title: "Workout session",
    category: "Health",
    description: "",
    color: "#720909",
    completed: false,
    createdAt: new Date(),
    completedAt: undefined,
  }
];